spring.datasource.url=jdbc:postgresql://localhost:5432/operion
spring.datasource.username=postgres
# LAPTOP B
 spring.datasource.password=postgres
# LAPTOP K
# spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=tIZ7Iceq4t6U5mqZNjU5BBBcAlOF49Np504WBjl/0Hl+cKoIQ1KrR8IeO87kSbId+5olTFlkwh3aHNCGbv8csA==